#pragma once

#include "NativeGameplayTags.h"

namespace PA_GameplayTags
{
	/* Input Tags */
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_CameraZoom);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip_DualWield);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnEquip_DualWield);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_Light_DualWield);

	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable);

	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld_Sprint);


	/* Player Tags */
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Sprint);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_DualWield);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_UnEquip_DualWield);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_DualWield);

	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_DualWield);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_UnEquip_DualWield);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_NextComboAttack);

	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_DualWield);

	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Sprinting);

	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);


	/* Enemy Tags */
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon_Goblin);


	/* Shared Tags */
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);

	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);
}
